export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const ITEMS_GET_START = "ITEMS_GET_START";
export const ITEMS_GET_SUCCESS = "ITEMS_GET_SUCCESS";
export const ITEMS_GET_FAIL = "ITEMS_GET_FAIl";