export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGIN_LOADING = "LOGIN_LOADING";
export const ITEMS_GET_SUCCESS = "ITEMS_GET_SUCCESS";
export const ITEMS_GET_FAILURE = "ITEMS_GET_FAILURE";
export const ITEMS_GET_LOADING = "ITEMS_GET_LOADING";